CREATE TABLE CHAPTER (
    ID NUMBER(38) PRIMARY KEY,
    TEXT VARCHAR2 NOT NULL
)

CREATE TABLE SUBCHAPTER (
    ID NUMBER(38) PRIMARY KEY,
    CHAPTER NUMBER(38),
    TEXT VARCHAR2 NOT NULL
)

CREATE TABLE TOPIC (
    ID NUMBER(38) PRIMARY KEY,
    SUBCHAPTER NUMBER(38),
    TEXT VARCHAR2 NOT NULL
)

CREATE TABLE TOPIC (
    ID NUMBER(38) PRIMARY KEY,
    SUBCHAPTER NUMBER(38),
    TEXT VARCHAR2 NOT NULL
)